export const CREATE_BOARD_START = 'CREATE_BOARD_START';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAIL = 'CREATE_BOARD_FAIL';
export const CLEAR_BOARD = 'CLEAR_BOARD';

export const CREATE_WORD_START = 'ADD_WORD_START';
export const CREATE_WORD_SUCCESS = 'ADD_WORD_SUCCESS';
export const CREATE_WORD_FAIL = 'CREATE_WORD_FAIL';
export const RESET_WORDS = 'RESET_WORDS';

export const SELECT_LETTER = 'SELECT_LETTER';
export const UNSELECT_LETTER = 'UNSELECT_LETTER';

export const ADD_TO_CURRENT_WORD = 'ADD_TO_CURRENT_WORD';
export const DELETE_FROM_CURRENT_WORD = 'DELETE_FROM_CURRENT_WORD';

export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';
export const UPDATE_GAME_TIME = 'UPDATE_GAME_TIME';
