export const CREATE_BOARD_START = 'CREATE_BOARD_START';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAIL = 'CREATE_BOARD_FAIL';

export const CREATE_WORD_START = 'ADD_WORD_START';
export const CREATE_WORD_SUCCESS = 'ADD_WORD_SUCCESS';
export const CREATE_WORD_FAIL = 'CREATE_WORD_FAIL';
